# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import  QGraphicsDropShadowEffect
from PyQt5.QtGui import QColor
from PyQt5.QtCore import pyqtSignal,pyqtSlot

import os
from settings_window.settings_window import settings_Window

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        current_dir = os.path.dirname(__file__)
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(893, 862)
        MainWindow.setStyleSheet("")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(
            "    #settingsButton{\n"
"                border: 2px solid #76ABAE; \n"
"                border-radius: 10px; \n"
"                padding: 8px 16px;\n"
"                background-color: #8ac8cb; \n"
"                color: #FFFFFF; \n"
"            }\n"
"\n"
"            #homeButton{\n"
"                border: 2px solid #76ABAE; \n"
"                border-radius: 10px; \n"
"                padding: 8px 16px;\n"
"                background-color: #8ac8cb; \n"
"                color: #FFFFFF; \n"
"            }\n"
"\n"
"            #homeButton:hover,#settingsButton:hover {\n"
"                background-color: #96d9dd; \n"
"            }\n"
"\n"
"\n"
"            #side_menu_frame {\n"
"                background-color:#31363F;\n"
"                border: 2px solid #76ABAE; \n"
"            }\n"
"\n"
"            #main_body_frame {\n"
"                background-color: #222831; \n"
"            }\n"
"\n"
"            #frame_2 {\n"
"                background-color: #222831; \n"
"                border: 7px solid red; \n"
"                border-radius: 40px; \n"
"            }\n"
"\n"
"            #top_body_frame ,#bottom_body_frame{\n"
"                background-color: #222831; \n"
"                border: 2px solid #76ABAE; \n"
"            }\n"
"            #frame{\n"
"                background-color: #222831;\n"
"            }\n"
"            #vaiot_response {\n"
"                background-color: #222831; \n"
"                color: #FFFFFF; \n"
"            }\n"
"\n"
"            /* Close button styles */\n"
"            #pushButton_4 {\n"
"                \n"
"                border:2px solid rgb(255, 20, 20);    \n"
"                border-radius: 10px; \n"
"                padding: 8px 16px; \n"
"                background-color: rgb(125, 74, 75);\n"
"                color: #FFFFFF; \n"
"            }\n"
"            #pushButton_4:hover {\n"
"                background-color: #e7898c; \n"
"            }\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.side_menu_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.side_menu_frame.sizePolicy().hasHeightForWidth())
        self.side_menu_frame.setSizePolicy(sizePolicy)
        self.side_menu_frame.setMinimumSize(QtCore.QSize(150, 566))
        self.side_menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.side_menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.side_menu_frame.setObjectName("side_menu_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.side_menu_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.homeButton = QtWidgets.QPushButton(self.side_menu_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.homeButton.sizePolicy().hasHeightForWidth())
        self.homeButton.setSizePolicy(sizePolicy)
        self.homeButton.setMinimumSize(QtCore.QSize(89, 50))
        self.homeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(f"{current_dir}/data/icons/door-home-home-page-homepage-house-svgrepo-com (1).svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.homeButton.setIcon(icon)
        self.homeButton.setIconSize(QtCore.QSize(30, 30))
        self.homeButton.setCheckable(False)
        self.homeButton.setObjectName("homeButton")
        self.verticalLayout_2.addWidget(self.homeButton, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.settingsButton = QtWidgets.QPushButton(self.side_menu_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsButton.sizePolicy().hasHeightForWidth())
        self.settingsButton.setSizePolicy(sizePolicy)
        self.settingsButton.setMinimumSize(QtCore.QSize(89, 50))
        self.settingsButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(f"{current_dir}/data/icons/settings-2-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsButton.setIcon(icon1)
        self.settingsButton.setIconSize(QtCore.QSize(30, 30))
        self.settingsButton.setCheckable(False)
        self.settingsButton.setObjectName("settingsButton")
        self.verticalLayout_2.addWidget(self.settingsButton, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.pushButton_4 = QtWidgets.QPushButton(self.side_menu_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(89, 50))
        self.pushButton_4.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(f"{current_dir}/data/icons/log-out-svgrepo-com.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_2.addWidget(self.pushButton_4, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout.addWidget(self.side_menu_frame)
        self.main_body_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_body_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.main_body_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body_frame.setObjectName("main_body_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.main_body_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_body_frame = QtWidgets.QFrame(self.main_body_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.top_body_frame.sizePolicy().hasHeightForWidth())
        self.top_body_frame.setSizePolicy(sizePolicy)
        self.top_body_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_body_frame.setObjectName("top_body_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_body_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.top_body_frame)
        self.frame.setMinimumSize(QtCore.QSize(400, 250))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(200, 200))
        self.frame_2.setMaximumSize(QtCore.QSize(200, 200))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(140, 140))
        self.pushButton.setStyleSheet("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setCheckable(True)
        self.pushButton.setStyleSheet(
            """
            QPushButton {
                background-color: #8ac8cb;
                border: 2px solid #8ac8cb;
                border-radius: 70px;
                color: #FFFFFF;
                font-size: 16px;
            }
            QPushButton:hover {
                background-color: #96d9dd;
                border-color: #96d9dd;
            }
        """
        )
        self.gridLayout_2.addWidget(self.pushButton, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout.addWidget(self.frame_2, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.top_body_frame)
        self.bottom_body_frame = QtWidgets.QFrame(self.main_body_frame)
        self.bottom_body_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_body_frame.setObjectName("bottom_body_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.bottom_body_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.vaiot_response = QtWidgets.QPlainTextEdit(self.bottom_body_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vaiot_response.sizePolicy().hasHeightForWidth())
        self.vaiot_response.setSizePolicy(sizePolicy)
        self.vaiot_response.setMinimumSize(QtCore.QSize(400, 250))
        self.vaiot_response.setObjectName("vaiot_response")
        self.horizontalLayout_3.addWidget(self.vaiot_response)
        self.verticalLayout.addWidget(self.bottom_body_frame)
        self.horizontalLayout.addWidget(self.main_body_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #signals form settings button to open settings page
        self.settingsButton.clicked.connect(self.open_settings_window)
        #signal form quit button to close the main window
        self.pushButton_4.clicked.connect(MainWindow.close)
        #signal to change frame color 
        self.pushButton.clicked.connect(self.animate_frame_border_color)


        self.shadow_effect = QGraphicsDropShadowEffect(self.frame_2)
        self.shadow_effect.setBlurRadius(30)
        self.shadow_effect.setOffset(QtCore.QPoint(0, 0))



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "START"))

    def animate_frame_border_color(self):
        if self.pushButton.isChecked():
            # Change the color to green (15, 255, 90) with full opacity (255)
            self.shadow_effect.setColor(QColor(15, 255, 90, 255))
            # Apply the effect to the button
            self.pushButton.setGraphicsEffect(self.shadow_effect)
            # self.frame_2.setStyleSheet('''
            # #frame_2 {
            # background-color: #222831;
            # border: 7px solid green;
            # border-radius: 40px;
            # }'''
            # )
        else:
            # Change the color to red (255, 0, 0) with full opacity (255)
            self.shadow_effect.setColor(QColor(255, 0, 0, 255))
            # Apply the effect to the button
            self.pushButton.setGraphicsEffect(self.shadow_effect)
            # self.frame_2.setStyleSheet('''
            # #frame_2 {
            # background-color: #222831;
            # border: 7px solid red;
            # border-radius: 40px;
            # }'''
            # )

    def open_settings_window(self):
        self.settings_window = QtWidgets.QMainWindow()
        self.ui = settings_Window()
        self.ui.setupUi(self.settings_window)
        self.settings_window.show()
    
    @QtCore.pyqtSlot(str)
    def printOnScreen(self,text :str):
        self.vaiot_response.appendPlainText(str(text))

    def clearOnScreen(self):
        self.vaiot_response.clear()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
